#!/usr/bin/env python3
"""Create Hugo directory indexes and one detail page per resource JSON file."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


GENERATED_MARKER = "# Generated by py_scrips/generate_resource_docs.py"


def display_title(stem: str) -> str:
    return " ".join(part.capitalize() for part in stem.split("_"))


def quote_toml(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def index_text(title: str, data_path: list[str]) -> str:
    fields = ["+++", f"title = {quote_toml(title)}", 'layout = "list"']
    if data_path:
        fields.append(f"resource_data_path = {json.dumps(data_path, ensure_ascii=False)}")
    fields.extend([GENERATED_MARKER, "+++", ""])
    return "\n".join(fields)


def page_text(stem: str, data_path: list[str]) -> str:
    return "\n".join(
        [
            "+++",
            f"title = {quote_toml(display_title(stem))}",
            'layout = "single"',
            f"resource_data_path = {json.dumps(data_path, ensure_ascii=False)}",
            f"resource_json = {quote_toml('/'.join(data_path) + '.json')}",
            GENERATED_MARKER,
            "+++",
            "",
        ]
    )


def valid_parts(path: Path) -> bool:
    return all(re.fullmatch(r"[A-Za-z0-9_-]+", part) for part in path.parts)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Sync Hugo resource sections and pages with generated JSON files."
    )
    parser.add_argument("--data-dir", type=Path, default=Path("data/generated/resources"))
    parser.add_argument("--content-dir", type=Path, default=Path("content/resources"))
    args = parser.parse_args()

    if not args.data_dir.is_dir():
        raise SystemExit(f"Resource data directory not found: {args.data_dir}")

    json_files = sorted(args.data_dir.rglob("*.json"), key=lambda p: p.as_posix().casefold())
    args.content_dir.mkdir(parents=True, exist_ok=True)
    expected_pages: set[Path] = set()

    root_index = args.content_dir / "_index.md"
    root_index.write_text(index_text("リソース", []), encoding="utf-8")
    expected_pages.add(root_index.resolve())

    directories: set[Path] = set()
    for json_path in json_files:
        directory = json_path.parent
        while directory != args.data_dir:
            directories.add(directory)
            directory = directory.parent
    sorted_directories = sorted(directories, key=lambda p: p.as_posix().casefold())
    for data_directory in sorted_directories:
        relative_directory = data_directory.relative_to(args.data_dir)
        if not valid_parts(relative_directory):
            print(f"Skipped unsupported directory: {relative_directory}")
            continue
        content_directory = args.content_dir / relative_directory
        content_directory.mkdir(parents=True, exist_ok=True)
        index_path = content_directory / "_index.md"
        data_parts = list(relative_directory.parts)
        index_path.write_text(index_text(display_title(data_parts[-1]), data_parts), encoding="utf-8")
        expected_pages.add(index_path.resolve())

    for json_path in json_files:
        relative = json_path.relative_to(args.data_dir)
        if not valid_parts(relative.with_suffix("")):
            print(f"Skipped unsupported filename: {relative}")
            continue
        page_path = args.content_dir / relative.with_suffix(".md")
        page_path.parent.mkdir(parents=True, exist_ok=True)
        data_path = list(relative.with_suffix("").parts)
        page_path.write_text(page_text(relative.stem, data_path), encoding="utf-8")
        expected_pages.add(page_path.resolve())
        print(f"Synced {relative} -> {page_path}")

    for page_path in args.content_dir.rglob("*.md"):
        if page_path.resolve() in expected_pages:
            continue
        try:
            generated = GENERATED_MARKER in page_path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            generated = False
        if generated:
            page_path.unlink()
            print(f"Removed stale page: {page_path}")

    for directory in sorted(args.content_dir.rglob("*"), reverse=True):
        if directory.is_dir() and not any(directory.iterdir()):
            directory.rmdir()

    print(f"Synced {len(json_files)} resource detail pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
