#!/usr/bin/env python3
"""Create one Hugo content page for each generated resource JSON file."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


GENERATED_MARKER = "# Generated by py_scrips/generate_resource_docs.py"


def display_title(stem: str) -> str:
    """Turn a snake_case JSON stem into a readable page title."""
    return " ".join(part.capitalize() for part in stem.split("_"))


def page_text(stem: str) -> str:
    return (
        "+++\n"
        f'title = "{display_title(stem)}"\n'
        f'resource_key = "{stem}"\n'
        f"{GENERATED_MARKER}\n"
        "+++\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Sync Hugo resource pages with generated JSON files."
    )
    parser.add_argument(
        "--data-dir",
        type=Path,
        default=Path("data/generated/resources"),
    )
    parser.add_argument(
        "--content-dir",
        type=Path,
        default=Path("content/resources"),
    )
    args = parser.parse_args()

    json_files = sorted(args.data_dir.glob("*.json"), key=lambda path: path.name.casefold())
    if not args.data_dir.is_dir():
        raise SystemExit(f"Resource data directory not found: {args.data_dir}")

    args.content_dir.mkdir(parents=True, exist_ok=True)
    expected_pages: set[Path] = set()
    for json_path in json_files:
        if not re.fullmatch(r"[A-Za-z0-9_-]+", json_path.stem):
            print(f"Skipped unsupported filename: {json_path.name}")
            continue
        page_path = args.content_dir / f"{json_path.stem}.md"
        page_path.write_text(page_text(json_path.stem), encoding="utf-8")
        expected_pages.add(page_path.resolve())
        print(f"Synced {json_path.name} -> {page_path}")

    for page_path in args.content_dir.glob("*.md"):
        if page_path.name == "_index.md" or page_path.resolve() in expected_pages:
            continue
        try:
            is_generated = GENERATED_MARKER in page_path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            is_generated = False
        if is_generated:
            page_path.unlink()
            print(f"Removed stale page: {page_path}")

    print(f"Synced {len(expected_pages)} resource documentation pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
