baseURL = "https://nanohatan.github.io/myGameMemo/"
locale = "ja-JP"
title = "My Game Memo"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT", "404"]

[params]
  description = "自作ゲームの記録を残すためのサイト"
