name: Deploy myGameMemo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout myGameMemo
        uses: actions/checkout@v4

      - name: Checkout private game
        uses: actions/checkout@v4
        with:
          repository: Nanohatan/GameSample
          token: ${{ secrets.PRIVATE_GAME_TOKEN }}
          path: _game